### ISSUE TITLE
Nor import nor require work for me

### ISSUE THREAD

**Issue by Zebiano** [LitoMore/chalk-pipe#1]
Sorry for this somewhat beginner question, as I feel like I'm missing something obvious here, but I'm not managing to run `chalk-pipe` on a freshly created node project. 

I've noticed inconsistency between the [`npm` README](https://www.npmjs.com/package/chalk-pipe) and the [GitHub README](https://github.com/LitoMore/chalk-pipe#usage):
```js
// npm
const chalkPipe = require('chalk-pipe');
console.log(chalkPipe('blue.bold')('Hello world!'));
```
```js
// GitHub
import chalkPipe from 'chalk-pipe';
console.log(chalkPipe('blue.bold')('Hello world!'));
```

Because of this I was unsure which way to run/use `chalk-pipe` and decided to test it out. After creating a new node (`v14.15.5`) project with just `npm i --save chalk-pipe` (`^5.0.0`) installed, I get errors whichever way I try. 

Using `require` yields the following:
```
$ node index.js 
internal/modules/cjs/loader.js:1080
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: X:\GitHub\Zebiano\test\node_modules\chalk-pipe\index.js
require() of ES modules is not supported.
require() of X:\GitHub\Zebiano\test\node_modules\chalk-pipe\index.js from X:\GitHub\Zebiano\test\index.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename X:\GitHub\Zebiano\test\node_modules\chalk-pipe\index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from X:\GitHub\Zebiano\test\node_modules\chalk-pipe\package.json.

←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (X:\GitHub\Zebiano\test\index.js:1:19)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m {
  code: ←[32m'ERR_REQUIRE_ESM'←[39m
}
```

And using `import` yields the following:
```
$ node index.js 
(node:9048) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
X:\GitHub\Zebiano\test\index.js:1
import chalkPipe from 'chalk-pipe';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```

Before trying to fix this myself and not really knowing what I'm doing, I preferred to create an issue and ask what the current intended way of importing this module is. Again, excuse me if I'm missing something obvious.

**Steps to reproduce:**
* `npm init -y`
* `npm i --save chalk-pipe`
* Create `index.js` file with either `import` or `require`
* `node index.js`

**Comment by LitoMore** [comment]
[chalk-pipe@5](https://github.com/LitoMore/chalk-pipe/releases/tag/5.0.0) is moved to [ESM](https://nodejs.org/dist/latest-v15.x/docs/api/esm.html#esm_enabling).

If you want CommonJS module, please use `chalk-pipe@4`.
